version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    shm_size: 128mb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - "server.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dailyhub"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  server:
    image: mathteushenrique/dailyhub-server:latest
    restart: always
    env_file:
      - "server.env"
    depends_on:
      - db
    volumes:
      - service_server:/app

volumes:
  postgres_data:
  service_server: